import PDFDocument from 'pdfkit';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

export interface PDFData {
  formTitle: string;
  legalText: string;
  signerName: string;
  signerEmail: string;
  signatureDataUrl: string;
  signedAt: Date;
  submissionId: number;
}

export async function generatePDF(data: PDFData): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'LETTER', margin: 50 });
      
      // Ensure output directory exists
      const outputDir = join(process.cwd(), 'public', 'submissions');
      mkdirSync(outputDir, { recursive: true });
      
      const filename = `submission-${data.submissionId}-${Date.now()}.pdf`;
      const filepath = join(outputDir, filename);
      const publicPath = `/submissions/${filename}`;
      
      // Create write stream
      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        writeFileSync(filepath, pdfBuffer);
        resolve(publicPath);
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text(data.formTitle, { align: 'center' });
      doc.moveDown();
      
      // Date
      doc.fontSize(10).font('Helvetica').text(
        `Signed: ${data.signedAt.toLocaleString('en-US', { 
          dateStyle: 'long', 
          timeStyle: 'short' 
        })}`,
        { align: 'right' }
      );
      doc.moveDown(2);

      // Signer info
      doc.fontSize(12).font('Helvetica-Bold').text('Signer Information:');
      doc.moveDown(0.5);
      doc.fontSize(11).font('Helvetica')
        .text(`Name: ${data.signerName}`)
        .text(`Email: ${data.signerEmail}`);
      doc.moveDown(2);

      // Legal text
      doc.fontSize(12).font('Helvetica-Bold').text('Agreement:');
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text(data.legalText, {
        align: 'justify',
        lineGap: 2
      });
      doc.moveDown(2);

      // Signature section
      doc.fontSize(12).font('Helvetica-Bold').text('Signature:');
      doc.moveDown(0.5);
      
      // Embed signature image
      if (data.signatureDataUrl && data.signatureDataUrl.startsWith('data:image')) {
        const base64Data = data.signatureDataUrl.split(',')[1];
        const imgBuffer = Buffer.from(base64Data, 'base64');
        doc.image(imgBuffer, { width: 200, height: 60 });
      } else {
        doc.fontSize(10).text('[Signature image not available]');
      }
      
      doc.moveDown();
      doc.fontSize(9).font('Helvetica-Oblique')
        .text('This document was signed electronically and is legally binding.', {
          align: 'center'
        });

      // Footer
      doc.fontSize(8).text(
        `Document ID: ${data.submissionId} | Generated by PaperOwl`,
        50,
        doc.page.height - 50,
        { align: 'center' }
      );

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
